import { relations, sql } from "drizzle-orm";
import { boolean, index, integer, jsonb, numeric, pgEnum, pgTable, text, timestamp, uniqueIndex, uuid, varchar } from "drizzle-orm/pg-core";

const timestamps = {
  createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow()
};

export const publicationStatus = pgEnum("es_publication_status", ["DRAFT", "PENDING_REVIEW", "APPROVED", "SCHEDULED", "PUBLISHED", "PAUSED", "EXPIRED", "CLOSED", "REJECTED", "DUPLICATE", "ARCHIVED"]);
export const verificationStatus = pgEnum("es_verification_status", ["UNVERIFIED", "SOURCE_CONFIRMED", "COMPANY_VERIFIED", "LINK_CONFIRMED", "NEEDS_REVIEW", "FAILED"]);
export const originType = pgEnum("es_origin_type", ["MANUAL", "SPREADSHEET", "API", "COMPANY_SUBMISSION", "INTERNAL_IMPORT", "OFFICIAL_SOURCE", "PARTNER"]);
export const contentType = pgEnum("es_content_type", ["NEWS", "GUIDE", "DATA_REPORT"]);
export const queueStatus = pgEnum("es_queue_status", ["PENDING", "PROCESSING", "COMPLETED", "FAILED", "CANCELLED"]);

export const states = pgTable("es_states", {
  id: uuid("id").primaryKey().defaultRandom(), legacyId: text("legacy_id").unique(), code: varchar("code", { length: 2 }).notNull().unique(), name: text("name").notNull(), slug: text("slug").notNull().unique(), ...timestamps
});
export const cities = pgTable("es_cities", {
  id: uuid("id").primaryKey().defaultRandom(), stateId: uuid("state_id").notNull().references(() => states.id), name: text("name").notNull(), slug: text("slug").notNull(), latitude: numeric("latitude"), longitude: numeric("longitude"), ...timestamps
}, (t) => [uniqueIndex("es_cities_state_slug_uq").on(t.stateId, t.slug)]);
export const companies = pgTable("es_companies", {
  id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull(), slug: text("slug").notNull().unique(), websiteUrl: text("website_url"), logoUrl: text("logo_url"), descriptionHtml: text("description_html"), verifiedAt: timestamp("verified_at", { withTimezone: true }), active: boolean("active").notNull().default(true), ...timestamps
});
export const categories = pgTable("es_categories", {
  id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull(), slug: text("slug").notNull().unique(), ...timestamps
});
export const users = pgTable("es_users", {
  id: uuid("id").primaryKey().defaultRandom(), email: text("email").notNull().unique(), name: text("name").notNull(), passwordHash: text("password_hash"), emailVerifiedAt: timestamp("email_verified_at", { withTimezone: true }), mfaEnabled: boolean("mfa_enabled").notNull().default(false), mfaSecretEncrypted: text("mfa_secret_encrypted"), mfaPendingSecretEncrypted: text("mfa_pending_secret_encrypted"), recoveryCodeHashes: jsonb("recovery_code_hashes").notNull().default([]), active: boolean("active").notNull().default(true), ...timestamps
});
export const roles = pgTable("es_roles", { id: uuid("id").primaryKey().defaultRandom(), key: text("key").notNull().unique(), name: text("name").notNull(), ...timestamps });
export const permissions = pgTable("es_permissions", { id: uuid("id").primaryKey().defaultRandom(), key: text("key").notNull().unique(), description: text("description"), ...timestamps });
export const userRoles = pgTable("es_user_roles", { userId: uuid("user_id").notNull().references(() => users.id), roleId: uuid("role_id").notNull().references(() => roles.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("es_user_roles_uq").on(t.userId, t.roleId)]);
export const rolePermissions = pgTable("es_role_permissions", { roleId: uuid("role_id").notNull().references(() => roles.id), permissionId: uuid("permission_id").notNull().references(() => permissions.id) }, (t) => [uniqueIndex("es_role_permissions_uq").on(t.roleId, t.permissionId)]);
export const sessions = pgTable("es_sessions", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id), tokenHash: text("token_hash").notNull().unique(), ipHash: text("ip_hash"), userAgentHash: text("user_agent_hash"), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), revokedAt: timestamp("revoked_at", { withTimezone: true }), ...timestamps });
export const passwordResetTokens = pgTable("es_password_reset_tokens", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const candidateSessions = pgTable("es_candidate_sessions", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), revokedAt: timestamp("revoked_at", { withTimezone: true }), ...timestamps });
export const magicLinkTokens = pgTable("es_magic_link_tokens", { id: uuid("id").primaryKey().defaultRandom(), userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), tokenHash: text("token_hash").notNull().unique(), expiresAt: timestamp("expires_at", { withTimezone: true }).notNull(), usedAt: timestamp("used_at", { withTimezone: true }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const userJobPreferences = pgTable("es_user_job_preferences", { userId: uuid("user_id").primaryKey().references(() => users.id, { onDelete: "cascade" }), cities: jsonb("cities").notNull().default([]), categories: jsonb("categories").notNull().default([]), workplaceTypes: jsonb("workplace_types").notNull().default([]), emailAlerts: boolean("email_alerts").notNull().default(false), ...timestamps });
export const loginAttempts = pgTable("es_login_attempts", { id: uuid("id").primaryKey().defaultRandom(), emailHash: text("email_hash").notNull(), ipHash: text("ip_hash").notNull(), successful: boolean("successful").notNull().default(false), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("es_login_attempts_rate_idx").on(t.emailHash, t.ipHash, t.createdAt)]);
export const jobs = pgTable("es_jobs", {
  id: uuid("id").primaryKey().defaultRandom(), publicCode: varchar("public_code", { length: 9 }).notNull().unique(), externalId: text("external_id"), slug: text("slug").notNull().unique(), originalTitle: text("original_title").notNull(), normalizedTitle: text("normalized_title").notNull(), companyId: uuid("company_id").notNull().references(() => companies.id), cityId: uuid("city_id").notNull().references(() => cities.id), stateId: uuid("state_id").notNull().references(() => states.id), categoryId: uuid("category_id").references(() => categories.id), neighborhood: text("neighborhood"), workplaceType: text("workplace_type").notNull().default("presencial"), employmentType: text("employment_type").notNull(), numberOfOpenings: integer("number_of_openings").notNull().default(1), salaryMin: numeric("salary_min"), salaryMax: numeric("salary_max"), salaryCurrency: varchar("salary_currency", { length: 3 }).notNull().default("BRL"), salaryPeriod: text("salary_period"), salaryVisible: boolean("salary_visible").notNull().default(false), summary: text("summary").notNull(), description: text("description").notNull(), activities: jsonb("activities").notNull().default([]), requirements: jsonb("requirements").notNull().default([]), benefits: jsonb("benefits").notNull().default([]), schedule: text("schedule"), education: text("education"), experienceLevel: text("experience_level"), pcd: boolean("pcd").notNull().default(false), applicationType: text("application_type").notNull().default("URL"), applicationUrl: text("application_url").notNull(), applicationEmail: text("application_email"), applicationWhatsapp: text("application_whatsapp"), sourceUrl: text("source_url"), sourceName: text("source_name").notNull(), sourceEvidence: text("source_evidence"), originType: originType("origin_type").notNull(), duplicateHash: text("duplicate_hash").notNull(), verificationStatus: verificationStatus("verification_status").notNull().default("UNVERIFIED"), publicationStatus: publicationStatus("publication_status").notNull().default("DRAFT"), publishedAt: timestamp("published_at", { withTimezone: true }), scheduledAt: timestamp("scheduled_at", { withTimezone: true }), expiresAt: timestamp("expires_at", { withTimezone: true }), closedAt: timestamp("closed_at", { withTimezone: true }), closureReason: text("closure_reason"), version: integer("version").notNull().default(1), featured: boolean("featured").notNull().default(false), sponsored: boolean("sponsored").notNull().default(false), sponsorDisclosure: text("sponsor_disclosure"), ...timestamps
}, (t) => [index("es_jobs_publication_idx").on(t.publicationStatus, t.publishedAt), index("es_jobs_location_idx").on(t.stateId, t.cityId), uniqueIndex("es_jobs_external_source_uq").on(t.externalId, t.sourceName)]);
export const savedJobs = pgTable("es_saved_jobs", { userId: uuid("user_id").notNull().references(() => users.id, { onDelete: "cascade" }), jobId: uuid("job_id").notNull().references(() => jobs.id, { onDelete: "cascade" }), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("es_saved_jobs_uq").on(t.userId, t.jobId)]);
export const jobRevisions = pgTable("es_job_revisions", { id: uuid("id").primaryKey().defaultRandom(), jobId: uuid("job_id").notNull().references(() => jobs.id), version: integer("version").notNull(), snapshot: jsonb("snapshot").notNull(), actorId: uuid("actor_id").references(() => users.id), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [uniqueIndex("es_job_revisions_uq").on(t.jobId, t.version)]);
export const jobSources = pgTable("es_job_sources", { id: uuid("id").primaryKey().defaultRandom(), jobId: uuid("job_id").notNull().references(() => jobs.id), name: text("name").notNull(), url: text("url").notNull(), externalId: text("external_id"), evidence: text("evidence"), lastCheckedAt: timestamp("last_checked_at", { withTimezone: true }), ...timestamps });
export const authors = pgTable("es_authors", { id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull(), slug: text("slug").notNull().unique(), bio: text("bio"), avatarUrl: text("avatar_url"), ...timestamps });
export const articles = pgTable("es_articles", { id: uuid("id").primaryKey().defaultRandom(), type: contentType("type").notNull(), authorId: uuid("author_id").notNull().references(() => authors.id), title: text("title").notNull(), slug: text("slug").notNull().unique(), excerpt: text("excerpt").notNull(), contentHtml: text("content_html").notNull(), coverImageUrl: text("cover_image_url"), status: publicationStatus("status").notNull().default("DRAFT"), publishedAt: timestamp("published_at", { withTimezone: true }), ...timestamps });
export const mediaAssets = pgTable("es_media_assets", { id: uuid("id").primaryKey().defaultRandom(), storageKey: text("storage_key").notNull().unique(), originalName: text("original_name").notNull(), mimeType: text("mime_type").notNull(), size: integer("size").notNull(), url: text("url").notNull(), altText: text("alt_text"), metadata: jsonb("metadata").notNull().default({}), ...timestamps });
export const redirects = pgTable("es_redirects", { id: uuid("id").primaryKey().defaultRandom(), sourcePath: text("source_path").notNull().unique(), destinationPath: text("destination_path").notNull(), statusCode: integer("status_code").notNull().default(301), active: boolean("active").notNull().default(true), ...timestamps });
export const importBatches = pgTable("es_import_batches", { id: uuid("id").primaryKey().defaultRandom(), fileHash: text("file_hash").notNull().unique(), fileName: text("file_name").notNull(), status: queueStatus("status").notNull().default("PENDING"), totalRows: integer("total_rows").notNull().default(0), validRows: integer("valid_rows").notNull().default(0), rejectedRows: integer("rejected_rows").notNull().default(0), settings: jsonb("settings").notNull().default({}), createdBy: uuid("created_by").references(() => users.id), undoneAt: timestamp("undone_at", { withTimezone: true }), undoneBy: uuid("undone_by").references(() => users.id), ...timestamps });
export const importMappingTemplates = pgTable("es_import_mapping_templates", { id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull().unique(), mapping: jsonb("mapping").notNull(), sheetName: text("sheet_name"), createdBy: uuid("created_by").references(() => users.id), ...timestamps });
export const importRows = pgTable("es_import_rows", { id: uuid("id").primaryKey().defaultRandom(), batchId: uuid("batch_id").notNull().references(() => importBatches.id), rowNumber: integer("row_number").notNull(), raw: jsonb("raw").notNull(), normalized: jsonb("normalized"), errors: jsonb("errors").notNull().default([]), action: text("action").notNull().default("REJECTED"), beforeSnapshot: jsonb("before_snapshot"), jobId: uuid("job_id").references(() => jobs.id), ...timestamps }, (t) => [uniqueIndex("es_import_rows_uq").on(t.batchId, t.rowNumber)]);
export const auditLogs = pgTable("es_audit_logs", { id: uuid("id").primaryKey().defaultRandom(), actorId: uuid("actor_id").references(() => users.id), action: text("action").notNull(), entityType: text("entity_type").notNull(), entityId: text("entity_id"), before: jsonb("before"), after: jsonb("after"), origin: text("origin").notNull(), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const backgroundJobs = pgTable("es_background_jobs", { id: uuid("id").primaryKey().defaultRandom(), queue: text("queue").notNull(), name: text("name").notNull(), bullJobId: text("bull_job_id"), status: queueStatus("status").notNull().default("PENDING"), payload: jsonb("payload").notNull(), attempts: integer("attempts").notNull().default(0), error: text("error"), scheduledAt: timestamp("scheduled_at", { withTimezone: true }), finishedAt: timestamp("finished_at", { withTimezone: true }), ...timestamps });
export const shortLinks = pgTable("es_short_links", { id: uuid("id").primaryKey().defaultRandom(), code: varchar("code", { length: 9 }).notNull().unique(), destinationUrl: text("destination_url").notNull(), entityType: text("entity_type"), entityId: uuid("entity_id"), clicks: integer("clicks").notNull().default(0), active: boolean("active").notNull().default(true), ...timestamps });
export const socialPosts = pgTable("es_social_posts", { id: uuid("id").primaryKey().defaultRandom(), entityType: text("entity_type").notNull(), entityId: uuid("entity_id").notNull(), format: text("format").notNull(), caption: text("caption").notNull(), altText: text("alt_text").notNull(), imageKey: text("image_key"), autoPublish: boolean("auto_publish").notNull().default(false), status: queueStatus("status").notNull().default("PENDING"), scheduledAt: timestamp("scheduled_at", { withTimezone: true }), approvedBy: uuid("approved_by").references(() => users.id), ...timestamps });
export const socialPublications = pgTable("es_social_publications", { id: uuid("id").primaryKey().defaultRandom(), postId: uuid("post_id").notNull().references(() => socialPosts.id), provider: text("provider").notNull().default("META"), externalContainerId: text("external_container_id"), externalMediaId: text("external_media_id"), status: queueStatus("status").notNull().default("PENDING"), attempts: integer("attempts").notNull().default(0), error: text("error"), publishedAt: timestamp("published_at", { withTimezone: true }), ...timestamps });
export const subscriptions = pgTable("es_subscriptions", { id: uuid("id").primaryKey().defaultRandom(), email: text("email").notNull().unique(), status: text("status").notNull().default("PENDING"), preferences: jsonb("preferences").notNull().default({}), confirmationTokenHash: text("confirmation_token_hash"), unsubscribeTokenHash: text("unsubscribe_token_hash").notNull(), confirmedAt: timestamp("confirmed_at", { withTimezone: true }), unsubscribedAt: timestamp("unsubscribed_at", { withTimezone: true }), ...timestamps });
export const alerts = pgTable("es_alerts", { id: uuid("id").primaryKey().defaultRandom(), subscriptionId: uuid("subscription_id").notNull().references(() => subscriptions.id), name: text("name").notNull(), filters: jsonb("filters").notNull(), frequency: text("frequency").notNull().default("DAILY"), active: boolean("active").notNull().default(true), ...timestamps });
export const notificationDeliveries = pgTable("es_notification_deliveries", { id: uuid("id").primaryKey().defaultRandom(), subscriptionId: uuid("subscription_id").references(() => subscriptions.id), channel: text("channel").notNull(), template: text("template").notNull(), providerId: text("provider_id"), status: queueStatus("status").notNull().default("PENDING"), error: text("error"), sentAt: timestamp("sent_at", { withTimezone: true }), ...timestamps });
export const consentLogs = pgTable("es_consent_logs", { id: uuid("id").primaryKey().defaultRandom(), subjectHash: text("subject_hash").notNull(), purpose: text("purpose").notNull(), action: text("action").notNull(), policyVersion: text("policy_version").notNull(), source: text("source").notNull(), ipHash: text("ip_hash"), userAgentHash: text("user_agent_hash"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() });
export const advertisers = pgTable("es_advertisers", { id: uuid("id").primaryKey().defaultRandom(), name: text("name").notNull(), document: text("document"), contactEmail: text("contact_email").notNull(), active: boolean("active").notNull().default(true), ...timestamps });
export const campaigns = pgTable("es_campaigns", { id: uuid("id").primaryKey().defaultRandom(), advertiserId: uuid("advertiser_id").notNull().references(() => advertisers.id), name: text("name").notNull(), status: text("status").notNull().default("DRAFT"), startsAt: timestamp("starts_at", { withTimezone: true }), endsAt: timestamp("ends_at", { withTimezone: true }), budget: numeric("budget"), disclosure: text("disclosure").notNull().default("Publicidade"), ...timestamps });
export const adSlots = pgTable("es_ad_slots", { id: uuid("id").primaryKey().defaultRandom(), key: text("key").notNull().unique(), pageType: text("page_type").notNull(), position: text("position").notNull(), active: boolean("active").notNull().default(false), reservedHeight: integer("reserved_height").notNull().default(280), ...timestamps });
export const adCreatives = pgTable("es_ad_creatives", { id: uuid("id").primaryKey().defaultRandom(), campaignId: uuid("campaign_id").notNull().references(() => campaigns.id), slotId: uuid("slot_id").notNull().references(() => adSlots.id), imageUrl: text("image_url").notNull(), destinationUrl: text("destination_url").notNull(), altText: text("alt_text").notNull(), active: boolean("active").notNull().default(true), ...timestamps });
export const adEvents = pgTable("es_ad_events", { id: uuid("id").primaryKey().defaultRandom(), creativeId: uuid("creative_id").references(() => adCreatives.id), slotKey: text("slot_key").notNull(), event: text("event").notNull(), path: text("path").notNull(), visitorHash: text("visitor_hash"), createdAt: timestamp("created_at", { withTimezone: true }).notNull().defaultNow() }, (t) => [index("es_ad_events_reporting_idx").on(t.slotKey, t.event, t.createdAt)]);
export const indexingEvents = pgTable("es_indexing_events", { id: uuid("id").primaryKey().defaultRandom(), dedupeKey: text("dedupe_key").notNull().unique(), jobId: uuid("job_id").references(() => jobs.id), provider: text("provider").notNull(), url: text("url").notNull(), notificationType: text("notification_type").notNull(), status: queueStatus("status").notNull().default("PENDING"), attempts: integer("attempts").notNull().default(0), response: jsonb("response"), error: text("error"), processedAt: timestamp("processed_at", { withTimezone: true }), ...timestamps }, (t) => [index("es_indexing_event_queue_idx").on(t.status, t.createdAt)]);
export const settings = pgTable("es_system_settings", { key: text("key").primaryKey(), value: jsonb("value").notNull(), public: boolean("public").notNull().default(false), updatedAt: timestamp("updated_at", { withTimezone: true }).notNull().defaultNow() });

export const jobRelations = relations(jobs, ({ one, many }) => ({ company: one(companies, { fields: [jobs.companyId], references: [companies.id] }), city: one(cities, { fields: [jobs.cityId], references: [cities.id] }), revisions: many(jobRevisions), sources: many(jobSources) }));
export const activePublishedJobs = sql`${jobs.publicationStatus} = 'PUBLISHED' and ${jobs.expiresAt} > now()`;
